<a href="https://colab.research.google.com/github/sayam-h069/2403A51L27_B51_PDS/blob/main/Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Question-1
import pandas as pd
import numpy as np

students_data = {
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'major': ['Math', 'Science', 'Math', 'History', 'Science']
}
students_df = pd.DataFrame(students_data)

scores_data = {
    'student_id': [101, 102, 103, 106],
    'score': [85, 92, 78, 88]
}
scores_df = pd.DataFrame(scores_data)

print("--- Students Dataset ---")
print(students_df)
print("\n--- Scores Dataset ---")
print(scores_df)

inner_merged_df = pd.merge(students_df, scores_df, on='student_id', how='inner')
print("\n--- Inner Join ---")
print(inner_merged_df)

left_merged_df = pd.merge(students_df, scores_df, on='student_id', how='left')
print("\n--- Left Join ---")
print(left_merged_df)

right_merged_df = pd.merge(students_df, scores_df, on='student_id', how='right')
print("\n--- Right Join ---")
print(right_merged_df)

print("\n--- Aggregate Statistics for Inner Join ---")
mean_score = inner_merged_df['score'].mean()
max_score = inner_merged_df['score'].max()
min_score = inner_merged_df['score'].min()
score_count = inner_merged_df['score'].count()

print(f"Mean Score: {mean_score:.2f}")
print(f"Max Score: {max_score}")
print(f"Min Score: {min_score}")
print(f"Count of Scores: {score_count}")

print("\n--- Descriptive Statistics Summary ---")
print(inner_merged_df['score'].describe())

print("\n--- Grouped Statistics by Major ---")
grouped_stats = inner_merged_df.groupby('major')['score'].agg(['mean', 'max', 'min', 'count'])
print(grouped_stats)

--- Students Dataset ---
   student_id     name    major
0         101    Alice     Math
1         102      Bob  Science
2         103  Charlie     Math
3         104    David  History
4         105      Eve  Science

--- Scores Dataset ---
   student_id  score
0         101     85
1         102     92
2         103     78
3         106     88

--- Inner Join ---
   student_id     name    major  score
0         101    Alice     Math     85
1         102      Bob  Science     92
2         103  Charlie     Math     78

--- Left Join ---
   student_id     name    major  score
0         101    Alice     Math   85.0
1         102      Bob  Science   92.0
2         103  Charlie     Math   78.0
3         104    David  History    NaN
4         105      Eve  Science    NaN

--- Right Join ---
   student_id     name    major  score
0         101    Alice     Math     85
1         102      Bob  Science     92
2         103  Charlie     Math     78
3         106      NaN      NaN     88

--- Aggregate Statistics for Inner Join ---
Mean Score: 85.00
Max Score: 92
Min Score: 78
Count of Scores: 3

--- Descriptive Statistics Summary ---
count     3.0
mean     85.0
std       7.0
min      78.0
25%      81.5
50%      85.0
75%      88.5
max      92.0
Name: score, dtype: float64

--- Grouped Statistics by Major ---
         mean  max  min  count
major
Math     81.5   85   78      2
Science  92.0   92   92      1

In [3]:
#question-2
import pandas as pd

customers_data = {
    'customer_id': [101, 102, 103, 104, 105, 106],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'region': ['North', 'South', 'North', 'East', 'South', 'West']
}
customers_df = pd.DataFrame(customers_data)
customers_df.to_csv('customers.csv', index=False)

sales_data = {
    'sale_id': range(1, 8),
    'customer_id': [101, 102, 103, 102, 105, 101, 105],
    'amount': [150.50, 200.00, 340.10, 55.75, 120.00, 99.99, 300.00]
}
sales_df = pd.DataFrame(sales_data)
sales_df.to_csv('sales.csv', index=False)

customers = pd.read_csv('customers.csv')
sales = pd.read_csv('sales.csv')

print("--- Customers Dataset ---")
print(customers)
print("\n--- Sales Dataset ---")
print(sales)

inner_join_df = pd.merge(customers, sales, on='customer_id', how='inner')
print("\n--- Merged Dataset (Inner Join) ---")
print(inner_join_df)

left_join_df = pd.merge(customers, sales, on='customer_id', how='left')
print("\n--- Merged Dataset (Left Join) ---")
print(left_join_df)

total_sales = inner_join_df['amount'].sum()
average_sale_value = inner_join_df['amount'].mean()

print("\n--- Overall Sales Statistics ---")
print(f"Total Sales: ${total_sales:,.2f}")
print(f"Average Sale Value: ${average_sale_value:,.2f}")

sales_per_customer = inner_join_df.groupby('name')['amount'].sum().reset_index()
print("\n--- Total Sales Per Customer ---")
print(sales_per_customer.sort_values(by='amount', ascending=False))

regional_sales = inner_join_df.groupby('region')['amount'].agg(['sum', 'mean', 'count'])
regional_sales = regional_sales.rename(columns={
    'sum': 'Total Sales',
    'mean': 'Average Sale',
    'count': 'Number of Sales'
})
print("\n--- Aggregate Sales Statistics by Region ---")
print(regional_sales.sort_values(by='Total Sales', ascending=False))

--- Customers Dataset ---
   customer_id     name region
0          101    Alice  North
1          102      Bob  South
2          103  Charlie  North
3          104    David   East
4          105      Eve  South
5          106    Frank   West

--- Sales Dataset ---
   sale_id  customer_id  amount
0        1          101  150.50
1        2          102  200.00
2        3          103  340.10
3        4          102   55.75
4        5          105  120.00
5        6          101   99.99
6        7          105  300.00

--- Merged Dataset (Inner Join) ---
   customer_id     name region  sale_id  amount
0          101    Alice  North        1  150.50
1          101    Alice  North        6   99.99
2          102      Bob  South        2  200.00
3          102      Bob  South        4   55.75
4          103  Charlie  North        3  340.10
5          105      Eve  South        5  120.00
6          105      Eve  South        7  300.00

--- Merged Dataset (Left Join) ---
   customer_id     name region  sale_id  amount
0          101    Alice  North      1.0  150.50
1          101    Alice  North      6.0   99.99
2          102      Bob  South      2.0  200.00
3          102      Bob  South      4.0   55.75
4          103  Charlie  North      3.0  340.10
5          104    David   East      NaN     NaN
6          105      Eve  South      5.0  120.00
7          105      Eve  South      7.0  300.00
8          106    Frank   West      NaN     NaN

--- Overall Sales Statistics ---
Total Sales: $1,266.34
Average Sale Value: $180.91

--- Total Sales Per Customer ---
      name  amount
3      Eve  420.00
2  Charlie  340.10
1      Bob  255.75
0    Alice  250.49

--- Aggregate Sales Statistics by Region ---
        Total Sales  Average Sale  Number of Sales
region
South        675.75    168.937500                4
North        590.59    196.863333                3